
logging:
  level:
    root: info
    com.musinsa: debug


spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.hbm2ddl.auto: create-drop
      hibernate.format_sql: true