server:
  error:
    include-exception: true
    include-stacktrace: always


logging:
  level:
    root: info
    com.musinsa: debug
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE


spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.hbm2ddl.auto: create-drop
      hibernate.format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:data/data.sql